# Function to take the uploaded response data
# pipeline(response)


#' The pipeline for calculation
#'
#' \code{pipeline} mainly using the \code{response} value in \code{template}
#' file to calculate drug combination effect related scores, including IC50,
#' synergy scores, CSS...
#'
#' \code{pipeline} function takes a data frame as input which must contain
#' variables: "block_id", "drug_row", "drug_col", "response", "conc_r", "conc_c",
#' "conc_r_unit", "conc_c_unit","cell_line_name".
#'
#' It will calculate and generate following 5 tables:
#' \enumerate{
#'   \item \strong{response_with_scores}: Synergy scores calculated in
#'   4 methods (ZIP, Bliss, Loewe, and HSA) via calling function
#'   \code{\link{GenerateScore}}.
#'   \item \strong{response_out}: "response" table in the form required by
#'   "Drug Comb" database.
#'   \item \strong{summary}: IC50, DSS, CSS scores for each blocks calculated by
#'   calling function \code{\link{GenerateSummary2}}.
#'   \item \strong{surface}: "surface" table for visualization generated by
#'   calling function \code{\link{GenerateSurface3}}.
#'   \item \strong{curve}: "curve" table for uploading to Drug Comb generated by
#'   calling function \code{\link{GenerateCurve}}
#' }
#'
#' @param response A data frame. It must contain variables: "block_id",
#' "drug_row", "drug_col", "response", "conc_r", "conc_c", "conc_r_unit",
#'  "conc_c_unit","cell_line_name"
#'
#' @return A list contains 5 data frames: "response_with_scores", "response",
#' "summary", "surface", "curve".
#'
#' @export
pipeline <- function(response) {

  options(scipen = 999) # suppress the scientific notation

  if (!all(c("block_id", "drug_row", "drug_col", "response", "conc_r",
             "conc_c", "conc_r_unit", "conc_c_unit","cell_line_name") %in%
           colnames(response)))
    stop("The input data must contain the following columns: ",
         "block_id, response, conc_r, conc_c, conc_r_unit, conc_c_unit, \n",
         "cell_line_name, drug_row, drug_col.")

  print(noquote('Generating scores...'))
  response_with_scores <- GenerateScore(response)
  response_out <- response_with_scores[, c("block_id", "conc_r", "conc_c",
                                           "response", "synergy_zip",
                                           "synergy_bliss", "synergy_loewe",
                                           "synergy_hsa")]

  print(noquote('Generating summary...'))
  summary <- GenerateSummary2(response_with_scores)

  print(noquote('Generating surface...'))
  surface <- GenerateSurface3(response_with_scores)

  print(noquote('Generating curve...'))
  curve <- GenerateCurve(response_with_scores)

  print(noquote('Ready.'))
  return(list(response_with_scores = response_with_scores,
              response = response_out,
              summary = summary,
              surface = surface,
              curve = curve))
}