# TidyComb
# Functions for processing drug response matrix.
# Copyrighte Shuyu Zheng
#
# Functions in this page:
#
# ImputeNear: Impute missing value with nearest values
# AddNoise: Add noise to response value
# ImputeIC50: Impute missing value at IC50 concentration of drug
# ExtractSingleDrug: Extract single drug response from matrix

#' Impute missing value with nearest values
#'
#' Function \code{ImputeNear} do missing value inputation by assigning the
#' average of values in nearest 4 cells (top, bottom, left, right) to the NA
#' cell.
#'
#' @param response.mat A matrix which has missing value.
#'
#' @param times a integer which refers to the time of runing imputation. The
#' default value is \code{1}, but sometimes you might want to run imputation
#' more than once.
#'
#' @return A matrix which is same as input matrix except the NA cells are filled
#' with numbers.
#'
#' @export
ImputeNear <- function(response.mat, times = 1) {
  for (i in seq(to = times)) {
  x <- array(c(rbind(response.mat[-1,], NA),
               rbind(NA, response.mat[-nrow(response.mat), ]),
               cbind(response.mat[,-1], NA),
               cbind(NA, response.mat[, -ncol(response.mat)])),
             dim=c(nrow(response.mat), ncol(response.mat), 4))
  x.imp <- apply(x, c(1,2), mean, na.rm = TRUE)
  index.na <- is.na(response.mat)
  response.mat[index.na] <- x.imp[index.na]
  }
  return(response.mat)
}

#' Add noise to response value
#'
#' Function \code{AddNoise} calculates and add a noise to values in response
#' matrix. The methods used to calculate noises are: "random" and "scale".
#'
#' There are two options for calculating noise in this function:
#' \itemize{
#'   \item \strong{random} The noises obey normal distribution ~N(0, 0.001).
#'   They are generated by fucntion \code{\link[stats]{rnorm}}.
#'   \item \strong{scale} The noises are generated by multiplying the total
#'   number of response values in matrix with 10^-10.
#' }
#'
#' @param response.df A data frame. It contains the response data for one block
#' of drug combination screen.
#'
#' @param method A characer. It refers to the method used for calculating noise.
#' Available options are "random" and "scale".
#'
#' @return A matrix. It contains the response value added with noises.
#'
#' @export

AddNoise <- function(response.df, method) {
  if (method == "random") {
    set.seed(1)
    noise <- stats::rnorm(nrow(response.df), 0, 0.001)
  # } else if (method == "scale") {
  #   scale <- 10^-10
  #   noise <- row(response.mat) * col(response.mat) * scale
  } else {
    stop('The available metods for adding noise are: "random" and "scale".')
  }
  response.df$response <- response.df$response + noise
  return(response.df)
}

#' Extract single drug response from matrix
#'
#' \code{ExtractSingleDrug} extracts the dose-response values of single drug (
#' drug added in column or row) from a drug combination dose-response matrix.
#'
#' @param response.mat A drug cobination dose-response matrix. It's column name
#' and row name are representing the concerntrations of drug added to column and
#' row, respectively. The values in matrix indicate the inhibition rate to cell
#' growth.
#'
#' @param dim A character. It should be either "col" or "row" to indicate which
#' drug's dose-response value will be extracted.
#'
#' @return A data frame. It contains two variables:
#' \itemize{
#' \item \strong{dose} The concertration of drug.
#' \item \strong{response} The cell's response (inhibation rate) to
#' corresponding drug concertration.
#' }
#'
#' @export
ExtractSingleDrug <- function(response.mat, dim = "row") {
  if (dim == "row") {
    single.drug <- data.frame(response = response.mat[, "0"],
                              dose = as.numeric(rownames(response.mat)))
  } else if (dim == "col") {
    single.drug <- data.frame(response = response.mat["0", ],
                              dose = as.numeric(colnames(response.mat)))
  } else {
    stop("Values for 'dim' should be eighther 'row' or 'col'!")
  }
  rownames(single.drug) <- NULL
  return(single.drug)
}
